"""Add enterprise governance models

Revision ID: c38fa6a71b44
Revises: 
Create Date: 2026-09-20 18:20:32.382599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38fa6a71b44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('target_file_id', sa.String(length=36), nullable=True),
    sa.Column('target_user_id', sa.String(length=36), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('action_details', sa.Text(), nullable=True),
    sa.Column('audit_log_id', sa.String(length=36), nullable=True),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_blocks_index'), 'audit_blocks', ['index'], unique=True)
    op.create_table('enterprise_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('stored_filename', sa.String(length=512), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('active_storage_path', sa.String(length=1024), nullable=True),
    sa.Column('quarantine_storage_path', sa.String(length=1024), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('retention_expires_at', sa.DateTime(), nullable=True),
    sa.Column('retention_hold', sa.Boolean(), nullable=True),
    sa.Column('recovered_at', sa.DateTime(), nullable=True),
    sa.Column('recovered_by', sa.String(length=36), nullable=True),
    sa.Column('purged_at', sa.DateTime(), nullable=True),
    sa.Column('purged_by', sa.String(length=36), nullable=True),
    sa.Column('erasure_method', sa.String(length=64), nullable=True),
    sa.Column('erasure_verified', sa.Boolean(), nullable=True),
    sa.Column('erasure_operation_id', sa.String(length=36), nullable=True),
    sa.Column('verification_result_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['erasure_operation_id'], ['erasure_operations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['purged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recovered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verification_result_id'], ['verification_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['enterprise_files.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recovery_requests')
    op.drop_table('enterprise_files')
    op.drop_index(op.f('ix_audit_blocks_index'), table_name='audit_blocks')
    op.drop_table('audit_blocks')
    # ### end Alembic commands ###
